---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by kang.
--- DateTime: 2023/12/4 11:31
---

result = my_int_add(1,37)
print("in [LUA] my_int_add, result = ", result)

result = my_string_combine('wang','kang')
print("in [LUA] my_string_combine, result = ", result)

result = my_combine('zhao','zuye')
print("in [LUA] my_combine, result = ", result)

result = my_combine(12,34)
print("in [LUA] my_combine, result = ", result)