---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by kang.
--- DateTime: 2023/12/4 11:31
---

print(" in [LUA] ")

--- 没有绑定对象的成员函数，需要把对象实例传入
fiftieth_value = my_class_func_2(obj)
print("in [LUA], fiftieth_value = ", fiftieth_value)

--- 已经绑定对象的实例，不需要传对象参数
sixth_value=my_class_func()
print("in [LUA], sixth_value = ", sixth_value)