---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by kang.
--- DateTime: 2023/12/4 16:21
---
p1 = player.new(2)

-- p2 is still here from being
-- set with lua["p2"] = player(0); below
local p2shoots = p2:shoot()
assert(not p2shoots)
-- had 0 ammo

-- set variable property setter
p1.hp = 545
-- get variable through property unqualified_getter
print(p1.hp)
assert(p1.hp == 545)

print('the bullets left ',p1.bullets)
local did_shoot_1 = p1:shoot()
print('shoot result ', did_shoot_1, ',the bullets left ',p1.bullets)
local did_shoot_2 = p1:shoot()
print('shoot result ', did_shoot_2, ',the bullets left ',p1.bullets)
local did_shoot_3 = p1:shoot()
print('shoot result ', did_shoot_3, ',the bullets left ',p1.bullets)

-- would error: is a readonly variable, cannot write
-- p1.bullets = 20

p1:boost()
-- call the function we define at runtime from a Lua script
p1:brake()